# Generated by Django 4.2.29 on 2026-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('nursing', '🩺 Nursing'), ('personal', '🌸 Personal'), ('relationship', '💕 Relationship')], max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('total_steps', models.IntegerField(default=5)),
                ('completed_steps', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['target_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('avg_sleep', models.FloatField(default=0)),
                ('total_water', models.IntegerField(default=0)),
                ('avg_stress', models.FloatField(default=0)),
                ('selfcare_rate', models.FloatField(default=0)),
                ('vitals_count', models.IntegerField(default=0)),
                ('journal_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
