# Generated by Django 4.2.29 on 2026-03-16 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_goal_wellnesssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_start', models.DateField(blank=True, null=True)),
                ('last_period_end', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(default=28)),
                ('period_length', models.IntegerField(default=5)),
                ('next_period_prediction', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('phase', models.CharField(choices=[('period', '🔴 Period'), ('pms', '💜 PMS'), ('ovulation', '💛 Ovulation'), ('regular', '💫 Regular')], default='regular', max_length=20)),
                ('flow', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=20)),
                ('pain_level', models.IntegerField(default=0)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('medication_taken', models.BooleanField(default=False)),
                ('water_reminder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
